#one nginx to foward proxy requests to our toy db instances
# load a permanenent volume that all toy db will write and read from

version: '3.3'
services:
  db:
    build: .
      context:
      dockerfile: toygraphdb.Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - .:/code
  proxy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    depends_on:
      - server
    ports:
      - "8080:8080"